version: "3.9"
services:
  db:
    container_name: db-zgamesusm
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: zgamesusm_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel1234
    networks:
      - net-zgamesusm
  web:
    container_name: zgamesusm-web
    depends_on:
      - db
    ports:
      - "8082:80"
    volumes:
      - "./web:/var/www/html"
      - "./httpd.conf:/etc/httpd/conf/httpd.conf"
    image: laravel-php8
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - net-zgamesusm
networks:
  net-zgamesusm:
    
